name = "saha-client"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[env.production]
vars = { NPM_FLAGS = "--legacy-peer-deps" }
