name = "saha-client"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[env.production.vars]
# Add production environment variables here if not using Cloudflare Dashboard
